run:
  timeout: 10m

linters:
  disable-all: true # Disable defaults, then enable the ones we want
  enable:
  - unused
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - unused
  - bodyclose
  - stylecheck
  - gosec
  - goimports
  - gci
  - revive
  - gocritic
  - unconvert

linters-settings:
  goimports:
    local-prefixes: github.com/ArmDeveloperEcosystem
  gci:
    sections:
    - Standard
    - Default
    - Prefix(github.com/ArmDeveloperEcosystem)
  testifylint:
    # Enable all checkers (https://github.com/Antonboom/testifylint#checkers).
    enable-all: true
