name: Main CI/CD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-go:
    runs-on: [github-ubuntu-22-04-arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"
          cache-dependency-path: "**/*.sum"

      - name: Download Go Modules
        run: go mod download

      - name: Test Go
        run: go test ./... --cover
