name: Main CI/CD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-go:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"

      - name: Install depedencies
        run: sudo apt-get install libbtrfs-dev -y

      - name: Download Go Modules
        run: go mod download

      - name: Test Go
        run: go test ./... --cover
