name: Main CI/CD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-go:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"

      - name: Install dependencies
        run: sudo apt-get install libbtrfs-dev -y

      - name: Download Go Modules
        run: go mod download

      - name: Linting
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: "--print-issued-lines --print-linter-name --out-${NO_FUTURE}format colored-line-number --timeout 300s --max-issues-per-linter 0 --max-same-issues 0"

      - name: Test Go
        run: go test ./... --cover
