name: Main CI/CD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-go:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Install dependencies
        run: sudo apt install libbtrfs-dev -y

      - name: Download Go Modules
        run: go mod download

      - name: Linting
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: "--no-config --timeout 5m"

      - name: Test Go
        run: go test ./... --cover
